export default class Problem {
    domCurrent

    static init(wrapper) {
        return new Problem(wrapper)
    }

    constructor(wrapper) {
        this.wrapper = wrapper

        wrapper.add('h1', 'Even Fibonacci numbers')
        wrapper.link('Problem 2', 'https://projecteuler.net/problem=2')
        wrapper.add('p','Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:')
        wrapper.add('center','1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...')
        wrapper.add('p','By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.')
        let c = wrapper.append('h3','0')
        this.domCurrent = c.el()
        c.to(wrapper.domContainer)
    }

    current(str) {
        this.domCurrent.innerHTML = str
    }

    main() {
        let msg = (str) => {
            console.log(str)
        }

        let total = 0
        let a = 1
        let b = 1
        let c = a + b

        let stop = 100

        while( c < 4000000 ) {
            if (stop-- <=0) break

            if (c%2 === 0) {
                total += c
            }
            a = b
            b = c
            c = a + b
            console.log(c)
        }

        this.current("result : "+ total)
    }
}